//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessToken
    {
        public System.Guid Id { get; set; }
        public System.DateTime ExpirationDate { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
