//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Resevations = new HashSet<Resevation>();
            this.CheckedOuts = new HashSet<CheckedOut>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime JoinDate { get; set; }
    
        public virtual ICollection<Resevation> Resevations { get; set; }
        public virtual ICollection<CheckedOut> CheckedOuts { get; set; }
    }
}
