//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryEntities : DbContext
    {
        public LibraryEntities()
            : base("name=LibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Librarian> Librarians { get; set; }
        public virtual DbSet<Resevation> Resevations { get; set; }
        public virtual DbSet<CheckedOut> CheckedOuts { get; set; }
        public virtual DbSet<OverDue> OverDues { get; set; }
        public virtual DbSet<Copy> Copies { get; set; }
        public virtual DbSet<Media> Media { get; set; }
        public virtual DbSet<AccessToken> AccessTokens { get; set; }
    }
}
